# Generated by Django 4.2.1 on 2023-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='core/comprobantes_subidos')),
                ('fehca_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
