# Generated by Django 4.2.1 on 2023-05-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comprobante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='operacion',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
