# Generated by Django 4.2.1 on 2023-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comprobante_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='core/comprobantes_subidos'),
        ),
    ]
