# Generated by Django 4.2.1 on 2023-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comprobante_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='operacion_multiple_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
